version: '3.1'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: helpdesk
      MYSQL_DATABASE: helpdesk
    ports:
      - "3306:3306"
